### PR TITLE
dependencies: update to angular 11

### PR DESCRIPTION
**Pull request by jma**
* Changes travis test in favour of github action.
* Removes locales from moment to reduce the bundle size.
* Create a custom distribution to remove the dependencies to avoid
  installing useless node package in the final application
* Removes multiple bootstrap inclusion.
* Create a new JSONSchema7 interface to add the form options.
* Updates third party dependencies, such as ngx-bootstrap, ngx-formly,
  etc.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Why are you opening this PR?

- angular 8 is end of life

## Dependencies

My PR depends on `ng-core#308`'s PR(s):

* https://github.com/rero/ng-core/pull/308

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

### CODE REVIEW

**Review by iGormilhit — COMMENTED** [review]
Commit title: from dependency to dependencies, mainly to be coherent with other commit titles.

**Review by zannkukai — APPROVED** [review]

**Review by AoNoOokami — COMMENTED** [review]
I found an issue with the `save as template` feature. Didn't find any other issue.

**Review by Garfield-fr — APPROVED** [review]

**Review by iGormilhit — CHANGES_REQUESTED** [review]
Commit message approved.

**Review by iGormilhit — APPROVED** [review]
Commit message approved.

**Pull request merged**
