### PR TITLE
admin: expand interface width and improve editor

### PR DESCRIPTION
**Pull request by AoNoOokami**
* Increases width of the menu.
* Increases width of 'body' content except for search results and
detailed views.
* Centers 'current library' information for harmonized display.
* Set a max width for selects and inputs in editor.
* Sets title font to bold.

Co-Authored-by: Alicia Zangger <alicia.zangger@rero.ch>

## Why are you opening this PR?

Implements task 1471 of US1296
https://tree.taiga.io/project/rero21-reroils/us/1296?milestone=263424
https://tree.taiga.io/project/rero21-reroils/task/1471?kanban-status=1224894

## Dependencies

https://github.com/rero/rero-ils/pull/1006
https://github.com/rero/ng-core/pull/184

## How to test?

Check the layout in different views of the admin interface.
Check the editor.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

### CODE REVIEW

**Comment by iGormilhit** [comment]
@AoNoOokami This is very nice!

For the search results views without facets, could the bootstrap columns be adjusted in order to leave the same left space blank? Maybe with this https://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns?

In [this issue](https://github.com/rero/rero-ils/issues/821), @pronguen propose to put the current library information in the user menu. In the issue, @pronguen provides a mockup proposition too. If it takes too much time, leave it to that issue.

**Comment by AoNoOokami** [comment]
> @AoNoOokami This is very nice!
> 
> For the search results views without facets, could the bootstrap columns be adjusted in order to leave the same left space blank? Maybe with this https://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns?
> 
> In [this issue](https://github.com/rero/rero-ils/issues/821), @pronguen propose to put the current library information in the user menu. In the issue, @pronguen provides a mockup proposition too. If it takes too much time, leave it to that issue.

As this US is a 'minimum effort' one, I will let this to the issue.

**Comment by AoNoOokami** [comment]
@iGormilhit An other PR improves some views: https://github.com/rero/ng-core/pull/182

**Comment by iGormilhit** [comment]
> @iGormilhit An other PR improves some views: [rero/ng-core#182](https://github.com/rero/ng-core/pull/182)

Ok, I'll have to test it, then. :slightly_smiling_face:

**Pull request merged**
